#define TARGET_IS_BLIZZARD_RB1
#define PART_TM4C123GH6PM
#include <stdbool.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdint.h>
#include "rom.h"
#include "sysctl.h"
#include "pin_map.h"
#include "hw_memmap.h"
#include "gpio.h"
#include "ssi.h"
#include "TM4C123GH6PM.h"